In [5]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

a[1,5]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


13

In [6]:
a.shape

(2, 7)

In [7]:
a[0:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [9]:
a[:,2]

array([ 3, 10])

In [11]:
a[0,1:-1:2] #row 0th starting from col index 1 until the end step up by 2 units

array([2, 4, 6])

In [12]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [13]:
np.ones((4,2,2),dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [15]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [17]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [18]:
np.identity(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
arr = np.array([[1,2,3],[4,5,6]])
r1 = np.repeat(arr,3,axis = 0) #axis = 0 if printing row wise 
#axis = 1 if printing column wise
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [32]:
a = np.array([(8,9,10),(11,12,13)])
print(a)
a = a.reshape(3,2) #reshape is not transpose
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]
